### PR TITLE
Add guard on classList function if element does not exist anymore

### LINKED ISSUE #103: Uncaught TypeError: Cannot read property 'className' of null
Uncaught TypeError: Cannot read property 'className' of null   nprogress.js:463
    classList                                                                                    nprogress.js:463
    removeClass                                                                             nprogress.js:444
    NProgress.remove                                                                    nprogress.js:257
    (anonymous function)                                                                 nprogress.js:98

### PR DESCRIPTION
**Pull request by martinratinaud**
Fix https://github.com/rstacruz/nprogress/issues/103

### CODE REVIEW

**Comment by abhilashlr** [comment]
Any updates on this merger?

**Comment by themre** [comment]
can this be merged?

**Comment by benheb** [comment]
Why did this never get merged?

**Comment by Landen13** [comment]
Please, merge this fix.

**Comment by hectorbus** [comment]
giphy

**Comment by danielbarion** [comment]
@rstacruz please take a look in that PR when you have time, thank you!

**Comment by danielbarion** [comment]
Omg, big mistake by me guys, this code is already [implemented](https://github.com/rstacruz/nprogress/blob/master/nprogress.js#L487) into the project.

@rstacruz can you do a release with that fix, please?

**Comment by patjagielski** [comment]
has there been a new release with this fix? I am still getting this error...

**Comment by martinratinaud** [comment]
I close this because it never got merged. Sorry

**Pull request closed without merging**
